// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Entities
{
    [Table("category")]
    public partial class Category
    {
        public Category()
        {
            ChannelCategories = new HashSet<ChannelCategory>();
        }

        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("name")]
        [StringLength(100)]
        public string Name { get; set; }
        [Column("platform_id")]
        public int PlatformId { get; set; }
        [Column("description")]
        public string Description { get; set; }

        [ForeignKey(nameof(PlatformId))]
        [InverseProperty("Categories")]
        public virtual Platform Platform { get; set; }
        [InverseProperty(nameof(ChannelCategory.Category))]
        public virtual ICollection<ChannelCategory> ChannelCategories { get; set; }
    }
}