// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess
{
    [Table("category")]
    public partial class Category
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("name")]
        [StringLength(100)]
        public string Name { get; set; }
        [Column("platform_id")]
        public int? PlatformId { get; set; }

        [ForeignKey(nameof(PlatformId))]
        [InverseProperty("Categories")]
        public virtual Platform Platform { get; set; }
    }
}