// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess
{
    [Table("channel_detail")]
    public partial class ChannelDetail
    {
        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("total_follow")]
        public long TotalFollow { get; set; }
        [Column("total_like")]
        public long TotalLike { get; set; }
        [Column("total_share")]
        public long? TotalShare { get; set; }
        [Column("total_comment")]
        public long TotalComment { get; set; }
        [Column("total_view")]
        public long? TotalView { get; set; }
        [Column("total_post")]
        public long TotalPost { get; set; }
        [Column("channel_id")]
        public long ChannelId { get; set; }

        [ForeignKey(nameof(ChannelId))]
        [InverseProperty("ChannelDetails")]
        public virtual Channel Channel { get; set; }
    }
}