// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Entities
{
    [Table("ChannelCategory")]
    public partial class ChannelCategory
    {
        [Key]
        [Column("channel_id")]
        public int ChannelId { get; set; }
        [Key]
        [Column("category_id")]
        public long CategoryId { get; set; }

        [ForeignKey(nameof(CategoryId))]
        [InverseProperty("ChannelCategories")]
        public virtual Category Category { get; set; }
        [ForeignKey(nameof(ChannelId))]
        [InverseProperty(nameof(ChannelCrawl.ChannelCategories))]
        public virtual ChannelCrawl Channel { get; set; }
    }
}