// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess
{
    [Table("channel_crawl")]
    public partial class ChannelCrawl
    {
        public ChannelCrawl()
        {
            PostCrawls = new HashSet<PostCrawl>();
        }

        [Key]
        [Column("id")]
        public long Id { get; set; }

        [InverseProperty("IdNavigation")]
        public virtual Channel Channel { get; set; }
        [InverseProperty(nameof(PostCrawl.Channel))]
        public virtual ICollection<PostCrawl> PostCrawls { get; set; }
    }
}