// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Entities
{
    [Table("channel_record")]
    public partial class ChannelRecord
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("total_follower")]
        public long TotalFollower { get; set; }
        [Column("total_like")]
        public long TotalLike { get; set; }
        [Column("total_share")]
        public long? TotalShare { get; set; }
        [Column("total_comment")]
        public long TotalComment { get; set; }
        [Column("total_post")]
        public long TotalPost { get; set; }
        [Column("total_view")]
        public long? TotalView { get; set; }
        [Column("channel_id")]
        public int ChannelId { get; set; }
        [Column("created_date", TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Column("update_date", TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }
        [Column("status")]
        public bool Status { get; set; }
        [ForeignKey(nameof(ChannelId))]
        [InverseProperty(nameof(ChannelCrawl.ChannelRecords))]
        public virtual ChannelCrawl Channel { get; set; }
    }
}