// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess
{
    [Table("channel")]
    public partial class Channel
    {
        public Channel()
        {
            ChannelDetails = new HashSet<ChannelDetail>();
            Ranks = new HashSet<Rank>();
        }

        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Required]
        [Column("cid")]
        [StringLength(50)]
        public string Cid { get; set; }
        [Required]
        [Column("name")]
        [StringLength(100)]
        public string Name { get; set; }
        [Column("url")]
        [StringLength(255)]
        public string Url { get; set; }
        [Column("avatar")]
        [StringLength(255)]
        public string Avatar { get; set; }
        [Column("banner")]
        [StringLength(255)]
        public string Banner { get; set; }
        [Column("phone")]
        [StringLength(15)]
        public string Phone { get; set; }
        [Column("address")]
        public string Address { get; set; }
        [Column("created_date", TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Column("update_date", TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }
        [Column("status")]
        public int? Status { get; set; }
        [Column("organization_name")]
        [StringLength(150)]
        public string OrganizationName { get; set; }
        [Column("member_id")]
        public int MemberId { get; set; }
        [Column("criteria_id")]
        public int CriteriaId { get; set; }
        [Column("location_id")]
        public int LocationId { get; set; }
        [Column("platform_id")]
        public int PlatformId { get; set; }
        [Column("nickname")]
        [StringLength(255)]
        public string Nickname { get; set; }

        [ForeignKey(nameof(CriteriaId))]
        [InverseProperty(nameof(Criterion.Channels))]
        public virtual Criterion Criteria { get; set; }
        [ForeignKey(nameof(Id))]
        [InverseProperty(nameof(ChannelManagement.Channel))]
        public virtual ChannelManagement Id1 { get; set; }
        [ForeignKey(nameof(Id))]
        [InverseProperty(nameof(ChannelCrawl.Channel))]
        public virtual ChannelCrawl IdNavigation { get; set; }
        [ForeignKey(nameof(LocationId))]
        [InverseProperty("Channels")]
        public virtual Location Location { get; set; }
        [ForeignKey(nameof(MemberId))]
        [InverseProperty(nameof(User.Channels))]
        public virtual User Member { get; set; }
        [ForeignKey(nameof(PlatformId))]
        [InverseProperty("Channels")]
        public virtual Platform Platform { get; set; }
        [InverseProperty(nameof(ChannelDetail.Channel))]
        public virtual ICollection<ChannelDetail> ChannelDetails { get; set; }
        [InverseProperty(nameof(Rank.Channel))]
        public virtual ICollection<Rank> Ranks { get; set; }
    }
}