// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess
{
    [Table("comment")]
    public partial class Comment
    {
        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("post_id")]
        public long PostId { get; set; }
        [Required]
        [Column("author_id")]
        [StringLength(50)]
        public string AuthorId { get; set; }
        [Required]
        [Column("author_name")]
        [StringLength(50)]
        public string AuthorName { get; set; }
        [Required]
        [Column("author_username")]
        [StringLength(50)]
        public string AuthorUsername { get; set; }
        [Column("created_date", TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Column("update_date", TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }
        [Required]
        [Column("message")]
        public string Message { get; set; }
        [Column("status")]
        public int Status { get; set; }
        [Column("reply_id")]
        public long? ReplyId { get; set; }
        [Column("comment_id")]
        public long CommentId { get; set; }

        [ForeignKey(nameof(PostId))]
        [InverseProperty(nameof(PostCrawl.Comments))]
        public virtual PostCrawl Post { get; set; }
    }
}