// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Entities
{
    [Table("feature")]
    public partial class Feature
    {
        public Feature()
        {
            FeaturePlans = new HashSet<FeaturePlan>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }
        [Column("description")]
        [StringLength(500)]
        public string Description { get; set; }
        [Column("type")]
        public int Type { get; set; }
        [Column("status")]
        public bool Status { get; set; }
        [Column("package_id")]
        public int PackageId { get; set; }

        [ForeignKey(nameof(PackageId))]
        [InverseProperty("Features")]
        public virtual Package Package { get; set; }
        [InverseProperty(nameof(FeaturePlan.Feature))]
        public virtual ICollection<FeaturePlan> FeaturePlans { get; set; }
    }
}