// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess
{
    [Table("hashtag_post")]
    public partial class HashtagPost
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }
        [Column("tag_id")]
        public int TagId { get; set; }

        [ForeignKey(nameof(TagId))]
        [InverseProperty(nameof(HashtagGroup.HashtagPosts))]
        public virtual HashtagGroup Tag { get; set; }
    }
}