// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess
{
    [Table("hashtag_group")]
    public partial class HashtagGroup
    {
        public HashtagGroup()
        {
            HashtagPosts = new HashSet<HashtagPost>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("hashtag_id")]
        public int HashtagId { get; set; }
        [Column("update_date", TypeName = "datetime")]
        public DateTime UpdateDate { get; set; }
        [Column("created_date", TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Column("status")]
        public int Status { get; set; }
        [Column("member_id")]
        public int MemberId { get; set; }

        [ForeignKey(nameof(MemberId))]
        [InverseProperty(nameof(User.HashtagGroups))]
        public virtual User Member { get; set; }
        [InverseProperty(nameof(HashtagPost.Tag))]
        public virtual ICollection<HashtagPost> HashtagPosts { get; set; }
    }
}