// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Entities
{
    [Table("hashtag")]
    public partial class Hashtag
    {
        public Hashtag()
        {
            PostHashtags = new HashSet<PostHashtag>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(255)]
        public string Name { get; set; }
        [Column("description")]
        [StringLength(255)]
        public string Description { get; set; }
        [Column("status")]
        public bool Status { get; set; }

        [InverseProperty(nameof(PostHashtag.Hashtag))]
        public virtual ICollection<PostHashtag> PostHashtags { get; set; }
    }
}