// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Entities
{
    [Table("hashtag")]
    public partial class Hashtag
    {
        public Hashtag()
        {
            PostCrawls = new HashSet<PostCrawl>();
            Posts = new HashSet<Post>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("name")]
        [StringLength(100)]
        public string Name { get; set; }

        [InverseProperty(nameof(PostCrawl.Hashtag))]
        public virtual ICollection<PostCrawl> PostCrawls { get; set; }
        [InverseProperty(nameof(Post.Hashtag))]
        public virtual ICollection<Post> Posts { get; set; }
    }
}