// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Entities
{
    [Table("location")]
    public partial class Location
    {
        public Location()
        {
            Channels = new HashSet<Channel>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [Column("code")]
        [StringLength(5)]
        public string Code { get; set; }

        [InverseProperty(nameof(Channel.Location))]
        public virtual ICollection<Channel> Channels { get; set; }
    }
}