// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess
{
    [Table("media_item")]
    public partial class MediaItem
    {
        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("size")]
        public int Size { get; set; }
        [Column("height")]
        public int Height { get; set; }
        [Column("width")]
        public int Width { get; set; }
        [Column("media_type_id")]
        public int MediaTypeId { get; set; }
        [Required]
        [Column("url")]
        [StringLength(50)]
        public string Url { get; set; }
        [Column("post_id")]
        public long PostId { get; set; }

        [ForeignKey(nameof(MediaTypeId))]
        [InverseProperty("MediaItems")]
        public virtual MediaType MediaType { get; set; }
        [ForeignKey(nameof(PostId))]
        [InverseProperty("MediaItems")]
        public virtual Post Post { get; set; }
    }
}