// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess
{
    [Table("media_type")]
    public partial class MediaType
    {
        public MediaType()
        {
            MediaItems = new HashSet<MediaItem>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty(nameof(MediaItem.MediaType))]
        public virtual ICollection<MediaItem> MediaItems { get; set; }
    }
}