// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Entities
{
    [Table("notification")]
    public partial class Notification
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("user_id")]
        public int UserId { get; set; }
        [Column("time_stamp", TypeName = "datetime")]
        public DateTime TimeStamp { get; set; }
        [Column("status")]
        public bool Status { get; set; }
        [Column("type")]
        [StringLength(20)]
        public string Type { get; set; }
        [Required]
        [Column("message")]
        [StringLength(500)]
        public string Message { get; set; }
        [Column("options")]
        public string Options { get; set; }
        [Column("isClick")]
        public bool IsClick { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("Notifications")]
        public virtual User User { get; set; }
    }
}