// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Entities
{
    [Table("order")]
    public partial class Order
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("note")]
        [StringLength(50)]
        public string Note { get; set; }
        [Column("created_date", TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Column("status")]
        public int Status { get; set; }
        [Column("total_money")]
        public int TotalMoney { get; set; }
        [Required]
        [Column("channel_id")]
        [StringLength(50)]
        public string ChannelId { get; set; }
        [Column("member_id")]
        public int MemberId { get; set; }
        [Column("update_date", TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }

        [ForeignKey(nameof(MemberId))]
        [InverseProperty(nameof(User.Orders))]
        public virtual User Member { get; set; }
    }
}