// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Entities
{
    [Table("package")]
    public partial class Package:BaseEntity
    {
        public Package()
        {
            Features = new HashSet<Feature>();
            Plans = new HashSet<Plan>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(255)]
        public string Name { get; set; }
        [Column("description")]
        public string Description { get; set; }
        [Column("status")]
        public bool Status { get; set; }

        [InverseProperty(nameof(Feature.Package))]
        public virtual ICollection<Feature> Features { get; set; }
        [InverseProperty(nameof(Plan.Package))]
        public virtual ICollection<Plan> Plans { get; set; }
    }
}