// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Entities
{
    [Table("plan")]
    public partial class Plan 
    {
        public Plan()
        {
            FeaturePlans = new HashSet<FeaturePlan>();
            PlanPrices = new HashSet<PlanPrice>();
            
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(100)]
        public string Name { get; set; }
        [Column("description")]
        public string Description { get; set; }
        [Column("status")]
        public bool Status { get; set; }

        [Column("package_id")]
        public int PackageId { get; set; }
        [Column("created_date", TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; } = DateTime.Now;
        [Column("update_date", TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; } = DateTime.Now;
        [ForeignKey(nameof(PackageId))]
        [InverseProperty("Plans")]
        public virtual Package Package { get; set; }
        [InverseProperty(nameof(FeaturePlan.Plan))]
        public virtual ICollection<FeaturePlan> FeaturePlans { get; set; }
        [InverseProperty(nameof(PlanPrice.Plan))]
        public virtual ICollection<PlanPrice> PlanPrices { get; set; }
       
    }
}