// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Entities
{
    [Table("plan_price")]
    public partial class PlanPrice
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("price_type")]
        public int PriceType { get; set; }
        [Column("price")]
        public double Price { get; set; }
        [Column("plan_id")]
        public int PlanId { get; set; }
        [Column("quantity")]
        public int Quantity { get; set; }

        [ForeignKey(nameof(PlanId))]
        [InverseProperty("PlanPrices")]
        public virtual Plan Plan { get; set; }
    }
}