// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess
{
    [Table("platform")]
    public partial class Platform
    {
        public Platform()
        {
            Categories = new HashSet<Category>();
            Channels = new HashSet<Channel>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }
        [Column("status")]
        public int Status { get; set; }

        [InverseProperty(nameof(Category.Platform))]
        public virtual ICollection<Category> Categories { get; set; }
        [InverseProperty(nameof(Channel.Platform))]
        public virtual ICollection<Channel> Channels { get; set; }
    }
}