// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess
{
    [Table("post_detail")]
    public partial class PostDetail
    {
        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("total_view")]
        public long? TotalView { get; set; }
        [Column("total_like")]
        public long TotalLike { get; set; }
        [Column("total_comment")]
        public long TotalComment { get; set; }
        [Column("total_share")]
        public long? TotalShare { get; set; }
        [Column("created_date", TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Column("update_date", TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }
        [Column("status")]
        public int Status { get; set; }
        [Column("post_id")]
        public long PostId { get; set; }

        [ForeignKey(nameof(PostId))]
        [InverseProperty(nameof(PostCrawl.PostDetails))]
        public virtual PostCrawl Post { get; set; }
    }
}