// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Entities
{
    [Table("post_crawl")]
    public partial class PostCrawl
    {
        public PostCrawl()
        {
            Comments = new HashSet<Comment>();
            PostDetails = new HashSet<PostDetail>();
            Reactions = new HashSet<Reaction>();
        }

        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Required]
        [Column("title")]
        [StringLength(50)]
        public string Title { get; set; }
        [Required]
        [Column("body")]
        public string Body { get; set; }
        [Column("update_at", TypeName = "datetime")]
        public DateTime? UpdateAt { get; set; }
        [Column("created_at", TypeName = "datetime")]
        public DateTime CreatedAt { get; set; }
        [Required]
        [Column("post_type")]
        [StringLength(50)]
        public string PostType { get; set; }
        [Column("status")]
        public int Status { get; set; }
        [Column("hashtag_id")]
        public int? HashtagId { get; set; }
        [Column("description")]
        public string Description { get; set; }
        [Required]
        [Column("pid")]
        [StringLength(50)]
        public string Pid { get; set; }
        [Column("channel_id")]
        public long ChannelId { get; set; }

        [ForeignKey(nameof(ChannelId))]
        [InverseProperty(nameof(ChannelCrawl.PostCrawls))]
        public virtual ChannelCrawl Channel { get; set; }
        [ForeignKey(nameof(HashtagId))]
        [InverseProperty("PostCrawls")]
        public virtual Hashtag Hashtag { get; set; }
        [InverseProperty(nameof(Comment.Post))]
        public virtual ICollection<Comment> Comments { get; set; }
        [InverseProperty(nameof(PostDetail.Post))]
        public virtual ICollection<PostDetail> PostDetails { get; set; }
        [InverseProperty(nameof(Reaction.Post))]
        public virtual ICollection<Reaction> Reactions { get; set; }
    }
}