// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess
{
    [Table("posts")]
    public partial class Post
    {
        public Post()
        {
            MediaItems = new HashSet<MediaItem>();
        }

        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Required]
        [Column("title")]
        [StringLength(50)]
        public string Title { get; set; }
        [Required]
        [Column("body")]
        public string Body { get; set; }
        [Column("update_date", TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }
        [Column("created_date", TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Column("status")]
        public int Status { get; set; }
        [Column("description")]
        [StringLength(255)]
        public string Description { get; set; }
        [Column("hashtag_id")]
        public int? HashtagId { get; set; }
        [Column("schedule_time", TypeName = "datetime")]
        public DateTime ScheduleTime { get; set; }
        [Column("post_type_id")]
        public int PostTypeId { get; set; }
        [Column("channel_id")]
        public long ChannelId { get; set; }
        [Column("pid")]
        [StringLength(50)]
        public string Pid { get; set; }

        [ForeignKey(nameof(ChannelId))]
        [InverseProperty(nameof(ChannelManagement.Posts))]
        public virtual ChannelManagement Channel { get; set; }
        [ForeignKey(nameof(HashtagId))]
        [InverseProperty("Posts")]
        public virtual Hashtag Hashtag { get; set; }
        [InverseProperty(nameof(MediaItem.Post))]
        public virtual ICollection<MediaItem> MediaItems { get; set; }
    }
}