// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Entities
{
    [Table("post_hashtag")]
    public partial class PostHashtag
    {
        [Key]
        [Column("post_id")]
        public int PostId { get; set; }
        [Key]
        [Column("hashtag_id")]
        public int HashtagId { get; set; }

        [ForeignKey(nameof(HashtagId))]
        [InverseProperty("PostHashtags")]
        public virtual Hashtag Hashtag { get; set; }
        [ForeignKey(nameof(PostId))]
        [InverseProperty(nameof(PostCrawl.PostHashtags))]
        public virtual PostCrawl Post { get; set; }
    }
}