// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess
{
    [Table("reaction")]
    public partial class Reaction
    {
        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("reaction_type_id")]
        public int ReactionTypeId { get; set; }
        [Column("post_id")]
        public long PostId { get; set; }
        [Required]
        [Column("username")]
        [StringLength(50)]
        public string Username { get; set; }
        [Required]
        [Column("display_name")]
        [StringLength(255)]
        public string DisplayName { get; set; }

        [ForeignKey(nameof(PostId))]
        [InverseProperty(nameof(PostCrawl.Reactions))]
        public virtual PostCrawl Post { get; set; }
        [ForeignKey(nameof(ReactionTypeId))]
        [InverseProperty("Reactions")]
        public virtual ReactionType ReactionType { get; set; }
    }
}