// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Entities
{
    [Table("reaction")]
    public partial class Reaction: BaseEntity
    {
        [Key]
        [Column("reaction_type_id")]
        public int ReactionTypeId { get; set; }
        [Key]
        [Column("post_id")]
        [StringLength(100)]
        public string PostId { get; set; }
        [Column("count")]
        public long Count { get; set; }
        [Column("status")]
        public bool Status { get; set; }

        [ForeignKey(nameof(PostId))]
        [InverseProperty(nameof(PostCrawl.Reactions))]
        public virtual PostCrawl Post { get; set; }
        [ForeignKey(nameof(ReactionTypeId))]
        [InverseProperty(nameof(Reactiontype.Reactions))]
        public virtual Reactiontype ReactionType { get; set; }
    }
}