// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Entities
{
    [Table("reaction")]
    public partial class Reaction
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("reaction_type_id")]
        public int ReactionTypeId { get; set; }
        [Column("post_id")]
        public int PostId { get; set; }
        [Column("count")]
        public long Count { get; set; }
        [Column("created_date", TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Column("update_date", TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }
        [Column("status")]
        public bool Status { get; set; }

        [ForeignKey(nameof(PostId))]
        [InverseProperty(nameof(PostCrawl.Reactions))]
        public virtual PostCrawl Post { get; set; }
        [ForeignKey(nameof(ReactionTypeId))]
        [InverseProperty(nameof(Reactiontype.Reactions))]
        public virtual Reactiontype ReactionType { get; set; }
    }
}