// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Entities
{
    [Table("reactiontype")]
    public partial class Reactiontype
    {
        public Reactiontype()
        {
            Reactions = new HashSet<Reaction>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }
        [Column("description")]
        [StringLength(255)]
        public string Description { get; set; }
        [Column("status")]
        public bool Status { get; set; }
        [Column("platform_id")]
        public int PlatformId { get; set; }

        [ForeignKey(nameof(PlatformId))]
        [InverseProperty("Reactiontypes")]
        public virtual Platform Platform { get; set; }
        [InverseProperty(nameof(Reaction.ReactionType))]
        public virtual ICollection<Reaction> Reactions { get; set; }
    }
}