// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Entities
{
    [Table("subscription")]
    public partial class Subscription:BaseEntity
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("price")]
        public double Price { get; set; }
        [Column("wallet_id")]
        public int WalletId { get; set; }
        [Column("user_id")]
        public int UserId { get; set; }
        [Column("status")]
        public int Status { get; set; }
        [Column("start_date", TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        [Column("end_date", TypeName = "datetime")]
        public DateTime EndDate { get; set; }
        [Column("plan_id")]
        public int PlanId { get; set; }
        [Column("plan_name")]
        [StringLength(50)]
        public string PlanName { get; set; }
        [ForeignKey(nameof(WalletId))]
        [InverseProperty("Subscriptions")]
        public virtual Wallet Wallet { get; set; }
    }
}