// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess
{
    [Table("target")]
    public partial class Target
    {
        public Target()
        {
            ChannelManagements = new HashSet<ChannelManagement>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("title")]
        [StringLength(100)]
        public string Title { get; set; }
        [Column("start_date", TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        [Column("end_date", TypeName = "datetime")]
        public DateTime EndDate { get; set; }
        [Column("progress")]
        public double? Progress { get; set; }
        [Column("target_type_id")]
        public int TargetTypeId { get; set; }
        [Column("created_date", TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Column("update_date", TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }
        [Column("status")]
        public int Status { get; set; }
        [Column("channel_id")]
        public long ChannelId { get; set; }

        [ForeignKey(nameof(TargetTypeId))]
        [InverseProperty("Targets")]
        public virtual TargetType TargetType { get; set; }
        [InverseProperty(nameof(ChannelManagement.Target))]
        public virtual ICollection<ChannelManagement> ChannelManagements { get; set; }
    }
}