// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess
{
    [Table("target_type")]
    public partial class TargetType
    {
        public TargetType()
        {
            Targets = new HashSet<Target>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(100)]
        public string Name { get; set; }
        [Column("description")]
        [StringLength(50)]
        public string Description { get; set; }
        [Required]
        [Column("field")]
        [StringLength(50)]
        public string Field { get; set; }

        [InverseProperty(nameof(Target.TargetType))]
        public virtual ICollection<Target> Targets { get; set; }
    }
}