// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Entities
{
    [Table("transaction_deposit")]
    public partial class TransactionDeposit
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("amount")]
        public int? Amount { get; set; }
        [Column("transaction_status")]
        [StringLength(5)]
        public string TransactionStatus { get; set; }
        [Column("response_code")]
        [StringLength(20)]
        public string ResponseCode { get; set; }
        [Column("trans_no_id")]
        public long? TransNoId { get; set; }
        [Column("pay_date", TypeName = "datetime")]
        public DateTime? PayDate { get; set; }
        [Column("order_infor")]
        [StringLength(50)]
        public string OrderInfor { get; set; }
        [Column("order_type")]
        [StringLength(10)]
        public string OrderType { get; set; }
        [Column("txn_ref")]
        public long TxnRef { get; set; }
        [Required]
        [Column("wallet_id")]
        public int WalletId { get; set; }
        [Column("tmn_code")]
        [StringLength(20)]
        public string TmnCode { get; set; }
        [Column("current_blance")]
        public int? CurrentBlance { get; set; }
        [Column("new_balance")]
        public int? NewBalance { get; set; }
        [Column("bank_code")]
        [StringLength(50)]
        public string BankCode { get; set; }
        [Column("bank_tran_no")]
        [StringLength(50)]
        public string BankTranNo { get; set; }
        [Column("card_type")]
        [StringLength(10)]
        public string CardType { get; set; }
        [Column("status")]
        public bool Status { get; set; }

        [ForeignKey(nameof(WalletId))]
        [InverseProperty("TransactionDeposits")]
        public virtual Wallet Wallet { get; set; }
    }
}