// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Entities
{
    [Table("user_type")]
    public partial class UserType
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("sub_id")]
        public int SubId { get; set; }
        [Column("plan_id")]
        public int PlanId { get; set; }
        [Column("date_start", TypeName = "datetime")]
        public DateTime DateStart { get; set; }
        [Column("date_end", TypeName = "datetime")]
        public DateTime DateEnd { get; set; }
        [Column("valid")]
        public bool Valid { get; set; }
        [Required]
        [Column("name")]
        [StringLength(100)]
        public string Name { get; set; }
        [Required]
        [Column("feature")]
        public string Feature { get; set; }
        [Column("user_id")]
        public int UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("UserType")]
        public virtual User User { get; set; }
    }
}