// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess
{
    [Table("user")]
    public partial class User
    {
        public User()
        {
            Channels = new HashSet<Channel>();
            HashtagGroups = new HashSet<HashtagGroup>();
            Orders = new HashSet<Order>();
            Wallets = new HashSet<Wallet>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("username")]
        [StringLength(30)]
        public string Username { get; set; }
        [Required]
        [Column("email")]
        [StringLength(50)]
        public string Email { get; set; }
        [Required]
        [Column("firstname")]
        [StringLength(20)]
        public string Firstname { get; set; }
        [Required]
        [Column("lastname")]
        [StringLength(20)]
        public string Lastname { get; set; }
        [Required]
        [Column("password")]
        [StringLength(255)]
        public string Password { get; set; }
        [Column("phone")]
        [StringLength(15)]
        public string Phone { get; set; }
        [Column("status")]
        public int Status { get; set; }
        [Column("last_login_at", TypeName = "datetime")]
        public DateTime? LastLoginAt { get; set; }
        [Column("created_date", TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Column("update_date", TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }
        [Column("role_id")]
        public int RoleId { get; set; }
        [Column("wallet_id")]
        public int WalletId { get; set; }
        [Column("fcm_token")]
        [MaxLength(255)]
        public byte[] FcmToken { get; set; }

        [ForeignKey(nameof(RoleId))]
        [InverseProperty("Users")]
        public virtual Role Role { get; set; }
        [InverseProperty(nameof(Channel.Member))]
        public virtual ICollection<Channel> Channels { get; set; }
        [InverseProperty(nameof(HashtagGroup.Member))]
        public virtual ICollection<HashtagGroup> HashtagGroups { get; set; }
        [InverseProperty(nameof(Order.Member))]
        public virtual ICollection<Order> Orders { get; set; }
        [InverseProperty(nameof(Wallet.Member))]
        public virtual ICollection<Wallet> Wallets { get; set; }
    }
}