// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Entities
{
    [Table("wallet")]
    public partial class Wallet
    {
        public Wallet()
        {
            TransactionDeposits = new HashSet<TransactionDeposit>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("balance")]
        public int Balance { get; set; }
        [Required]
        [Column("status")]
        [StringLength(10)]
        public string Status { get; set; }
        [Required]
        [Column("currency")]
        [StringLength(10)]
        public string Currency { get; set; }
        [Column("userr_id")]
        public int UserrId { get; set; }

        [ForeignKey(nameof(UserrId))]
        [InverseProperty(nameof(User.Wallets))]
        public virtual User Userr { get; set; }
        [InverseProperty(nameof(TransactionDeposit.Wallet))]
        public virtual ICollection<TransactionDeposit> TransactionDeposits { get; set; }
    }
}