// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Entities
{
    [Table("wallet")]
    public partial class Wallet:BaseEntity
    {

        public Wallet()
        {
            Subscriptions = new HashSet<Subscription>();
            TransactionDeposits = new HashSet<TransactionDeposit>();
        }
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("balance")]
        public int Balance { get; set; }
        [Required]
        [Column("status")]
        public bool Status { get; set; }
        [Required]
        [Column("currency")]
        [StringLength(5)]
        public string Currency { get; set; }
        [Column("user_id")]
        public int UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("Wallet")]
        public virtual User User { get; set; }
        [InverseProperty(nameof(Subscription.Wallet))]
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        [InverseProperty(nameof(TransactionDeposit.Wallet))]
        public virtual ICollection<TransactionDeposit> TransactionDeposits { get; set; }
    }
}